version: '3.8'

services:
  app_srv:
    build:
      context: .
      target: base
      dockerfile: ./Dockerfile
    command: yarn start:dev
    links:
      - redis
      - postgres
    ports:
      # 8080 is the default port
      - ${SERVER_EXTERNAL_PORT:-7574}:${SERVER_PORT:-8080}
    volumes:
      - ./locales/:/home/node/app/locales/
      - ./.env:/home/node/app/.env
    networks:
      - ystuty_network
    healthcheck:
      test: curl --fail http://localhost:${SERVER_PORT:-8080}/uptime || exit 1
      interval: 2m
      retries: 3
      start_period: 40s
      timeout: 10s
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  postgres:
    image: postgres:14
    # ports:
    #   - ${POSTGRES_EXTERNAL_PORT:-5431}:${POSTGRES_PORT:-5432}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE:-ystuty-schedule-bot}
    networks:
      - ystuty_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    links:
      - postgres
    ports:
      - ${PGADMIN_WEB_PORT:-5033}:80
    volumes:
      # Hint: `sudo chown -R 5050:5050`
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD?}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    networks:
      - ystuty_network
    restart: unless-stopped

  redis:
    image: 'redis:alpine'
    volumes:
      - ./redis-data:/data
    networks:
      - ystuty_network
    restart: unless-stopped

networks:
  ystuty_network:
    external:
      name: ystuty_network
